version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
  
  rabbitmq:
    image: rabbitmq:3
    ports:
      - "5672:5672"